Add tools from pixel beat http://www.pixelbeat.org/scripts/
Signed-off-by: Mahyuddin Susanto <udienz@gmail.com>

diff --git a/timeout b/timeout
--- a/timeout
+++ b/timeout
@@ -1,193 +1,57 @@
-#!/usr/bin/perl -w
+#!/bin/sh
 
-=head1 NAME
+# Execute a command with a timeout
 
-timeout - Run a command and kill it after the given period.
+# License: LGPLv2
+# Author:
+#    http://www.pixelbeat.org/
+# Notes:
+#    Note there is a timeout command packaged with coreutils since v7.0
+#    If the timeout occurs the exit status is 124.
+#    There is an asynchronous (and buggy) equivalent of this
+#    script packaged with bash (under /usr/share/doc/ in my distro),
+#    which I only noticed after writing this.
+#    I noticed later again that there is a C equivalent of this packaged
+#    with satan by Wietse Venema, and copied to forensics by Dan Farmer.
+# Changes:
+#    V1.0, Nov  3 2006, Initial release
+#    V1.1, Nov 20 2007, Brad Greenlee <brad@footle.org>
+#                       Make more portable by using the 'CHLD'
+#                       signal spec rather than 17.
+#    V1.3, Oct 29 2009, Ján Sáreník <jasan@x31.com>
+#                       Even though this runs under dash,ksh etc.
+#                       it doesn't actually timeout. So enforce bash for now.
+#                       Also change exit on timeout from 128 to 124
+#                       to match coreutils.
+#    V2.0, Oct 30 2009, Ján Sáreník <jasan@x31.com>
+#                       Rewritten to cover compatibility with other
+#                       Bourne shell implementations (pdksh, dash)
 
-=cut
+if [ "$#" -lt "2" ]; then
+    echo "Usage:   `basename $0` timeout_in_seconds command" >&2
+    echo "Example: `basename $0` 2 sleep 3 || echo timeout" >&2
+    exit 1
+fi
 
-
-=head1 SYNOPSIS
-
-  General Options:
-
-   --timeout   Specify the maximum execution time.
-   --help      Show the help information for this script.
-   --verbose   Show useful debugging information.
-
-=cut
-
-
-=head1 ABOUT
-
-This command will allow you to run a subcommand and terminate
-that after the given time.
-
-You may specify the timeout period in either seconds, minutes and
-seconds, or hours, minutes and seconds.  For example:
-
-=for example begin
-
-    # kill after 32 seconds
-    timeout -t 32 top
-
-    # kill after two minutes, five seconds
-    timeout -t 2:5 top
-
-    # kill after six hour, five minutes, and two seconds.
-    timeout -t 6:5:2 top
-
-=for example end
-
-The timeout period is mandatory and has no default.
-
-=cut
-
-=head1 AUTHOR
-
- Steve
- --
- http://www.steve.org.uk/
-
-=cut
-
-
-=head1 LICENSE
-
-Copyright (c) 2013 by Steve Kemp.  All rights reserved.
-
-This script is free software; you can redistribute it and/or modify it under
-the same terms as Perl itself.
-
-The LICENSE file contains the full text of the license.
-
-=cut
-
-use strict;
-use warnings;
-
-use Getopt::Long;
-use Pod::Usage;
-
-
-
-#
-#  Get the options, either defaults or from the command line.
-#
-my %config = parsedOptions();
-
-#
-#  Ensure we have a timeotut
-#
-if ( !$config{ 'timeout' } )
+cleanup()
 {
-    print "Please specify a timeout.\n";
-    exit(2);
+    trap - ALRM               #reset handler to default
+    kill -ALRM $a 2>/dev/null #stop timer subshell if running
+    kill $! 2>/dev/null &&    #kill last job
+      exit 124                #exit with 124 if it was running
 }
 
-#
-#  If we're being verbose..
-#
-if ( $config{ 'verbose' } )
+watchit()
 {
-    print "Running command: " . join( " ", @ARGV ) . "\n";
-    print "Max executiong time " . $config{ 'timeout' } . " seconds\n";
-
+    trap "cleanup" ALRM
+    sleep $1& wait
+    kill -ALRM $$
 }
 
-#
-#  Call the command we were given, with our timeout.
-#
-timed_system( $config{ 'timeout' }, @ARGV );
-
-#
-# All done.
-#
-exit(0);
-
-
-sub timed_system
-{
-    my $time = shift;
-    my $pid;
-
-    local $SIG{ ALRM } = sub {
-        kill 15, $pid or die "kill: $!";
-        die "Timeout!";
-    };    # Just SIGTERM.
-    eval {
-        $pid = fork;
-        die "Fork failed: $!" unless defined $pid;
-        unless ($pid)
-        {
-            exec @_;
-            die "Exec failed: $!";
-        }
-        alarm $time;
-        waitpid $pid => 0;
-    };
-    die $@ if $@ && $@ !~ /^Timeout!/;
-}
-
-
-
-=begin doc
-
-Parse the command line options (minimal!)
-
-=end doc
-
-=cut
-
-sub parsedOptions
-{
-    my %vars;
-
-    exit
-      if (
-           !GetOptions( "help"      => \$vars{ 'help' },
-                        "timeout=s" => \$vars{ 'timeout' },
-                        "verbose"   => \$vars{ 'verbose' } ) );
-
-    pod2usage(1) if ( $vars{ 'help' } );
-
-    if ( !$vars{ 'timeout' } )
-    {
-        print "Please specify a timeout\n";
-        exit(2);
-    }
-
-
-    #
-    #  HH:MM:SS
-    #
-    if ( $vars{ 'timeout' } =~ /^([0-9]+):([0-9]+):([0-9]+)$/ )
-    {
-        my $sec = $3 + ( 60 * $2 ) + ( 60 * 60 * $1 );
-        $vars{ 'timeout' } = $sec;
-    }
-    elsif ( $vars{ 'timeout' } =~ /^([0-9]+):([0-9]+)$/ )
-    {
-
-        #
-        # MM:SS
-        #
-        my $sec = $2 + ( 60 * $1 );
-        $vars{ 'timeout' } = $sec;
-    }
-    elsif ( $vars{ 'timeout' } =~ /^([0-9]+)$/ )
-    {
-
-        #
-        #  SS
-        #
-    }
-    else
-    {
-        print "Invalid timeout specification\n";
-        exit(2);
-    }
-
-    return (%vars);
-
-}
+watchit $1& a=$!         #start the timeout
+shift                    #first param was timeout for sleep
+trap "cleanup" ALRM INT  #cleanup after timeout
+"$@"& wait $!; RET=$?    #start the job wait for it and save its return value
+kill -ALRM $a            #send ALRM signal to watchit
+wait $a                  #wait for watchit to finish cleanup
+exit $RET                #return the value
